In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Input_csv/2018hitting_combined.csv")
df

,Rk,Player,HR,Year,Age,Tm,Lg,G,PA,AB,...,SH,SF,GDP,SB,CS,BA,OBP,SLG,OPS,Pos
0,1.0,Khris Davis,48.0,2018.0,30.0,OAK,AL,151.0,654.0,576.0,...,0.0,7.0,16.0,0.0,0.0,0.247,0.326,0.549,0.874,*D7/H
1,2.0,J.D. Martinez,43.0,2018.0,30.0,BOS,AL,150.0,649.0,569.0,...,0.0,7.0,19.0,6.0,1.0,0.330,0.402,0.629,1.031,D79
2,3.0,Joey Gallo,40.0,2018.0,24.0,TEX,AL,148.0,577.0,500.0,...,0.0,0.0,3.0,3.0,4.0,0.206,0.312,0.498,0.810,7398H/D
3,4.0,Jose Ramirez,39.0,2018.0,25.0,CLE,AL,157.0,698.0,578.0,...,0.0,6.0,2.0,34.0,6.0,0.270,0.387,0.552,0.939,*54/D
4,5.0,Mike Trout,39.0,2018.0,26.0,LAA,AL,140.0,608.0,471.0,...,0.0,4.0,5.0,24.0,2.0,0.312,0.460,0.629,1.088,*8D/H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,1268.0,Daniel Zamora,0.0,2018.0,25.0,NYM,NL,15.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,*1
1268,1269.0,Rob Zastryzny,0.0,2018.0,26.0,CHC,NL,6.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,/1
1269,1270.0,Brad Ziegler,0.0,2018.0,38.0,TOT,NL,76.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,*1
1270,1271.0,Jordan Zimmermann,0.0,2018.0,32.0,DET,AL,2.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000,*1
1271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Isolate relevant columns 
df = df[['Player', 'G', 'PA', 'AB', 'H', '2B', '3B', 'HR', 'SB', 'CS', 'BB', 'HBP', 'SH', 'SF']]
df

,Player,G,PA,AB,H,2B,3B,HR,SB,CS,BB,HBP,SH,SF
0,Khris Davis,151.0,654.0,576.0,142.0,28.0,1.0,48.0,0.0,0.0,59.0,12.0,0.0,7.0
1,J.D. Martinez,150.0,649.0,569.0,188.0,37.0,2.0,43.0,6.0,1.0,69.0,4.0,0.0,7.0
2,Joey Gallo,148.0,577.0,500.0,103.0,24.0,1.0,40.0,3.0,4.0,74.0,3.0,0.0,0.0
3,Jose Ramirez,157.0,698.0,578.0,156.0,38.0,4.0,39.0,34.0,6.0,106.0,8.0,0.0,6.0
4,Mike Trout,140.0,608.0,471.0,147.0,24.0,4.0,39.0,24.0,2.0,122.0,10.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,Daniel Zamora,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1268,Rob Zastryzny,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1269,Brad Ziegler,76.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1270,Jordan Zimmermann,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#Create column for singles
df['1B'] = df['H'] - df['2B'] - df['3B'] - df['HR']
df.columns

C:\Users\eanma\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['Player', 'G', 'PA', 'AB', 'H', '2B', '3B', 'HR', 'SB', 'CS', 'BB',
       'HBP', 'SH', 'SF', '1B'],
      dtype='object')

In [5]:
#Reorder columns
df = df[['Player', 'G', 'PA', 'AB', 'H', '1B', '2B', '3B', 'HR', 'SB', 'CS',
       'BB', 'HBP', 'SH', 'SF']]
#https://www.kite.com/python/answers/how-to-reorder-columns-in-a-pandas-dataframe-in-python
df

,Player,G,PA,AB,H,1B,2B,3B,HR,SB,CS,BB,HBP,SH,SF
0,Khris Davis,151.0,654.0,576.0,142.0,65.0,28.0,1.0,48.0,0.0,0.0,59.0,12.0,0.0,7.0
1,J.D. Martinez,150.0,649.0,569.0,188.0,106.0,37.0,2.0,43.0,6.0,1.0,69.0,4.0,0.0,7.0
2,Joey Gallo,148.0,577.0,500.0,103.0,38.0,24.0,1.0,40.0,3.0,4.0,74.0,3.0,0.0,0.0
3,Jose Ramirez,157.0,698.0,578.0,156.0,75.0,38.0,4.0,39.0,34.0,6.0,106.0,8.0,0.0,6.0
4,Mike Trout,140.0,608.0,471.0,147.0,80.0,24.0,4.0,39.0,24.0,2.0,122.0,10.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,Daniel Zamora,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1268,Rob Zastryzny,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1269,Brad Ziegler,76.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1270,Jordan Zimmermann,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
weights = {'1B':1, '2B':2, '3B':3, 'HR':4, 'SB':1, 'CS':-1, 'BB':1, 'HBP':1, 'SH':1, 'SF':1}
df['TBp'] = (weights['1B']*df['1B'] + weights['2B']*df['2B'] + weights['3B']*df['3B'] + weights['HR']*df['HR'] + 
            weights['SB']*df['SB'] + weights['CS']*df['CS'] + weights['BB']*df['BB'] + weights['HBP']*df['HBP'] +
            weights['SH']*df['SH'] + weights['SF']*df['SF'])
df

C:\Users\eanma\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,Player,G,PA,AB,H,1B,2B,3B,HR,SB,CS,BB,HBP,SH,SF,TBp
0,Khris Davis,151.0,654.0,576.0,142.0,65.0,28.0,1.0,48.0,0.0,0.0,59.0,12.0,0.0,7.0,394.0
1,J.D. Martinez,150.0,649.0,569.0,188.0,106.0,37.0,2.0,43.0,6.0,1.0,69.0,4.0,0.0,7.0,443.0
2,Joey Gallo,148.0,577.0,500.0,103.0,38.0,24.0,1.0,40.0,3.0,4.0,74.0,3.0,0.0,0.0,325.0
3,Jose Ramirez,157.0,698.0,578.0,156.0,75.0,38.0,4.0,39.0,34.0,6.0,106.0,8.0,0.0,6.0,467.0
4,Mike Trout,140.0,608.0,471.0,147.0,80.0,24.0,4.0,39.0,24.0,2.0,122.0,10.0,0.0,4.0,454.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,Daniel Zamora,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1268,Rob Zastryzny,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1269,Brad Ziegler,76.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1270,Jordan Zimmermann,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.sort_values(by = ['TBp'], ascending = False, inplace = True)
df

C:\Users\eanma\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Player,G,PA,AB,H,1B,2B,3B,HR,SB,CS,BB,HBP,SH,SF,TBp
3,Jose Ramirez,157.0,698.0,578.0,156.0,75.0,38.0,4.0,39.0,34.0,6.0,106.0,8.0,0.0,6.0,467.0
4,Mike Trout,140.0,608.0,471.0,147.0,80.0,24.0,4.0,39.0,24.0,2.0,122.0,10.0,0.0,4.0,454.0
20,Mookie Betts,136.0,614.0,520.0,180.0,96.0,47.0,5.0,32.0,30.0,6.0,81.0,8.0,0.0,5.0,451.0
1,J.D. Martinez,150.0,649.0,569.0,188.0,106.0,37.0,2.0,43.0,6.0,1.0,69.0,4.0,0.0,7.0,443.0
6,Francisco Lindor,158.0,745.0,661.0,183.0,101.0,42.0,2.0,38.0,25.0,10.0,70.0,8.0,3.0,3.0,442.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,Andrew Miller,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
952,Ben Meyer,13.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
700,Danny Duffy,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1270,Jordan Zimmermann,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df = df.reset_index(drop = True)
df

,Player,G,PA,AB,H,1B,2B,3B,HR,SB,CS,BB,HBP,SH,SF,TBp
0,Jose Ramirez,157.0,698.0,578.0,156.0,75.0,38.0,4.0,39.0,34.0,6.0,106.0,8.0,0.0,6.0,467.0
1,Mike Trout,140.0,608.0,471.0,147.0,80.0,24.0,4.0,39.0,24.0,2.0,122.0,10.0,0.0,4.0,454.0
2,Mookie Betts,136.0,614.0,520.0,180.0,96.0,47.0,5.0,32.0,30.0,6.0,81.0,8.0,0.0,5.0,451.0
3,J.D. Martinez,150.0,649.0,569.0,188.0,106.0,37.0,2.0,43.0,6.0,1.0,69.0,4.0,0.0,7.0,443.0
4,Francisco Lindor,158.0,745.0,661.0,183.0,101.0,42.0,2.0,38.0,25.0,10.0,70.0,8.0,3.0,3.0,442.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,Andrew Miller,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1268,Ben Meyer,13.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1269,Danny Duffy,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1270,Jordan Zimmermann,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.head(20)

,Player,G,PA,AB,H,1B,2B,3B,HR,SB,CS,BB,HBP,SH,SF,TBp
0,Jose Ramirez,157.0,698.0,578.0,156.0,75.0,38.0,4.0,39.0,34.0,6.0,106.0,8.0,0.0,6.0,467.0
1,Mike Trout,140.0,608.0,471.0,147.0,80.0,24.0,4.0,39.0,24.0,2.0,122.0,10.0,0.0,4.0,454.0
2,Mookie Betts,136.0,614.0,520.0,180.0,96.0,47.0,5.0,32.0,30.0,6.0,81.0,8.0,0.0,5.0,451.0
3,J.D. Martinez,150.0,649.0,569.0,188.0,106.0,37.0,2.0,43.0,6.0,1.0,69.0,4.0,0.0,7.0,443.0
4,Francisco Lindor,158.0,745.0,661.0,183.0,101.0,42.0,2.0,38.0,25.0,10.0,70.0,8.0,3.0,3.0,442.0
5,Christian Yelich,147.0,651.0,574.0,187.0,110.0,34.0,7.0,36.0,22.0,4.0,68.0,7.0,0.0,2.0,438.0
6,Alex Bregman,157.0,705.0,594.0,170.0,87.0,51.0,1.0,31.0,10.0,4.0,96.0,12.0,0.0,3.0,433.0
7,Manny Machado,162.0,709.0,632.0,188.0,113.0,35.0,3.0,37.0,14.0,2.0,70.0,2.0,0.0,5.0,429.0
8,Bryce Harper,159.0,695.0,550.0,137.0,69.0,34.0,0.0,34.0,13.0,3.0,130.0,6.0,0.0,9.0,428.0
9,Trevor Story,157.0,656.0,598.0,174.0,89.0,42.0,6.0,37.0,27.0,6.0,47.0,7.0,0.0,4.0,418.0
10,Paul Goldschmidt,158.0,690.0,593.0,172.0,99.0,35.0,5.0,33.0,7.0,4.0,90.0,6.0,0.0,0.0,415.0
11,Nolan Arenado,156.0,673.0,590.0,175.0,97.0,38.0,2.0,38.0,2.0,2.0,73.0,3.0,1.0,6.0,414.0
12,Matt Carpenter,156.0,677.0,564.0,145.0,67.0,42.0,0.0,36.0,4.0,1.0,102.0,6.0,0.0,4.0,410.0
13,Freddie Freeman,162.0,707.0,618.0,191.0,120.0,44.0,4.0,23.0,10.0,3.0,76.0,7.0,0.0,6.0,408.0
14,Giancarlo Stanton,158.0,705.0,617.0,164.0,91.0,34.0,1.0,38.0,5.0,0.0,70.0,8.0,0.0,10.0,407.0
15,Khris Davis,151.0,654.0,576.0,142.0,65.0,28.0,1.0,48.0,0.0,0.0,59.0,12.0,0.0,7.0,394.0
16,Charlie Blackmon,156.0,696.0,626.0,182.0,115.0,31.0,7.0,29.0,12.0,4.0,59.0,8.0,1.0,2.0,392.0
17,Whit Merrifield,158.0,707.0,632.0,192.0,134.0,43.0,3.0,12.0,45.0,10.0,61.0,6.0,2.0,6.0,387.0
18,Javier Baez,160.0,645.0,606.0,176.0,93.0,40.0,9.0,34.0,21.0,9.0,29.0,5.0,1.0,4.0,387.0
19,Mitch Haniger,157.0,683.0,596.0,170.0,102.0,38.0,4.0,26.0,8.0,2.0,70.0,10.0,0.0,7.0,387.0

In [10]:
df['TBp / PA'] = df['TBp']/df['PA']
df.sort_values(by = ['TBp / PA'], ascending = False, inplace = True)
df = df.loc[df['PA'] > 100]
df = df.reset_index(drop = True)
df.head(20)

,Player,G,PA,AB,H,1B,2B,3B,HR,SB,CS,BB,HBP,SH,SF,TBp,TBp / PA
0,Mike Trout,140.0,608.0,471.0,147.0,80.0,24.0,4.0,39.0,24.0,2.0,122.0,10.0,0.0,4.0,454.0,0.746711
1,Mookie Betts,136.0,614.0,520.0,180.0,96.0,47.0,5.0,32.0,30.0,6.0,81.0,8.0,0.0,5.0,451.0,0.734528
2,Luke Voit,47.0,161.0,143.0,46.0,26.0,5.0,0.0,15.0,0.0,0.0,17.0,1.0,0.0,0.0,114.0,0.708075
3,J.D. Martinez,150.0,649.0,569.0,188.0,106.0,37.0,2.0,43.0,6.0,1.0,69.0,4.0,0.0,7.0,443.0,0.682589
4,Christian Yelich,147.0,651.0,574.0,187.0,110.0,34.0,7.0,36.0,22.0,4.0,68.0,7.0,0.0,2.0,438.0,0.672811
5,Jose Ramirez,157.0,698.0,578.0,156.0,75.0,38.0,4.0,39.0,34.0,6.0,106.0,8.0,0.0,6.0,467.0,0.669054
6,Max Muncy,137.0,481.0,395.0,104.0,50.0,17.0,2.0,35.0,3.0,0.0,79.0,5.0,0.0,2.0,319.0,0.663202
7,Ryan O'Hearn,44.0,170.0,149.0,39.0,15.0,10.0,2.0,12.0,0.0,0.0,20.0,1.0,0.0,0.0,110.0,0.647059
8,Trevor Story,157.0,656.0,598.0,174.0,89.0,42.0,6.0,37.0,27.0,6.0,47.0,7.0,0.0,4.0,418.0,0.637195
9,Shohei Ohtani,104.0,367.0,326.0,93.0,48.0,21.0,2.0,22.0,10.0,4.0,37.0,2.0,0.0,1.0,230.0,0.626703
10,Ronald Acuna Jr.,111.0,487.0,433.0,127.0,71.0,26.0,4.0,26.0,16.0,5.0,45.0,6.0,0.0,3.0,304.0,0.624230
11,Bryce Harper,159.0,695.0,550.0,137.0,69.0,34.0,0.0,34.0,13.0,3.0,130.0,6.0,0.0,9.0,428.0,0.615827
12,Nolan Arenado,156.0,673.0,590.0,175.0,97.0,38.0,2.0,38.0,2.0,2.0,73.0,3.0,1.0,6.0,414.0,0.615156
13,Aaron Judge,112.0,498.0,413.0,115.0,66.0,22.0,0.0,27.0,6.0,3.0,76.0,4.0,0.0,5.0,306.0,0.614458
14,Alex Bregman,157.0,705.0,594.0,170.0,87.0,51.0,1.0,31.0,10.0,4.0,96.0,12.0,0.0,3.0,433.0,0.614184
15,Adalberto Mondesi,75.0,291.0,275.0,76.0,46.0,13.0,3.0,14.0,32.0,7.0,11.0,1.0,3.0,1.0,178.0,0.611684
16,Matt Carpenter,156.0,677.0,564.0,145.0,67.0,42.0,0.0,36.0,4.0,1.0,102.0,6.0,0.0,4.0,410.0,0.605613
17,Manny Machado,162.0,709.0,632.0,188.0,113.0,35.0,3.0,37.0,14.0,2.0,70.0,2.0,0.0,5.0,429.0,0.605078
18,Khris Davis,151.0,654.0,576.0,142.0,65.0,28.0,1.0,48.0,0.0,0.0,59.0,12.0,0.0,7.0,394.0,0.602446
19,Paul Goldschmidt,158.0,690.0,593.0,172.0,99.0,35.0,5.0,33.0,7.0,4.0,90.0,6.0,0.0,0.0,415.0,0.601449

In [11]:
df.to_csv('Output_csv/2018TBp.csv', index = False)